services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: This1is2just3a4test!
      POSTGRES_DB: questions_and_answers
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy  # Ожидание, пока база данных не станет доступна
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:This1is2just3a4test!@db:5432/questions_and_answers"

volumes:
  pgdata: