services:
  db:
    ports:
      - "5432:5432"
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: This1is2just3a4test!
      POSTGRES_DB: questions_and_answers
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:This1is2just3a4test!@db:5432/questions_and_answers"

volumes:
  pgdata: